# Generated by Django 4.2 on 2024-08-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('hourly', 'раз в час'), ('daily', 'раз в день'), ('weekly', 'раз в неделю')], default='daily', max_length=10, verbose_name='периодичность'),
        ),
    ]
