# Generated by Django 4.2 on 2024-08-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_options_habit_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
    ]
