# Generated by Django 4.2 on 2024-09-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='habit',
            name='periodicity_every',
            field=models.IntegerField(default=1, verbose_name='каждое кол-во дней'),
        ),
    ]
